name: Configure AWS
description: Setup AWS credentials using repo secrets
author: Segev Grotas

inputs:
  aws_access_key:
    description: "AWS Access Key"
    required: true
  aws_secret_key:
    description: "AWS Secret Key"
    required: true
  aws_region:
    description: "AWS Region"
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws_access_key }}
        aws-secret-access-key: ${{ inputs.aws_secret_key }}
        aws-region: ${{ inputs.aws_region }}
