name: Configure AWS
description: Setup AWS credentials using repo secrets
author: Segev Grotas

inputs:
  aws_role_arn:
    description: "AWS permissions Role"
    required: true
  aws_region:
    description: "AWS Region"
    required: true

runs:
  using: "composite"
  steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.aws_role_arn }}
          aws-region: ${{ inputs.aws_region }}
