services:
  frontend:
    container_name: jamlive-frontend
    image: jamlive/frontend:test
    build:
      context: ./frontend
      args:
        REACT_APP_BASE_URL: ${REACT_APP_BASE_URL}
    ports:
      - "80:3000"
    networks:
      - frontend-network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:3000 || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      backend:
        condition: service_healthy

  backend:
    image: jamlive/backend:test
    container_name: jamlive-backend
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - frontend-network
      - backend-network
    healthcheck:
      test:
        ["CMD-SHELL", "wget -q --spider http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mongo:6
    container_name: jamlive-db
    volumes:
      - db_data:/data/db
      - ./backend/db/seed:/docker-entrypoint-initdb.d
    networks:
      - backend-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'mongosh --quiet --eval ''db.adminCommand("ping").ok'' localhost:27017 | grep 1',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  frontend-network:
  backend-network:

volumes:
  db_data:
