services:
  frontend:
    image: jamlive-front:test
    build:
      context: ./frontend
      args:
        REACT_APP_BASE_URL: ${REACT_APP_BASE_URL}
    ports:
      - "80:3000"
    networks:
      - frontend-network
    depends_on:
      - backend
  backend:
    image: jamlive-back:test
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - frontend-network
      - backend-network

  db:
    image: mongo:6
    container_name: jamlive-db
    volumes:
      - db_data:/data/db
      - ./backend/db/seed:/docker-entrypoint-initdb.d
    networks:
      - backend-network

networks:
  frontend-network:
  backend-network:

volumes:
  db_data:
