services:
  frontend:
    image: jamlive-front:test
    build:
      context: ./frontend
    ports:
      - "80:3000"
    environment:
      - REACT_APP_BASE_URL=${REACT_APP_BASE_URL}
    networks:
      - jamLive
    depends_on:
      - backend
    volumes:
      - ./frontend_build:/app/build

  backend:
    image: jamlive-back:test
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - JWT_COOKIE_EXPIRES_IN=${JWT_COOKIE_EXPIRES_IN}
      - FRONTEND_ORIGIN=${FRONTEND_ORIGIN}
      - E2E_BASE_URL=${E2E_BASE_URL}
    networks:
      - jamLive

networks:
  jamLive: