name: E2E Tests
description: Run end-to-end Playwright tests
author: Segev Grotas

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: "20.10.0"
        cache: "npm"
        cache-dependency-path: "e2e/package-lock.json"

    - name: Store/Restore Playwright browsers cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          playwright-${{ runner.os }}-

    - name: Install Dependencies
      working-directory: e2e
      run: |
        npm ci
        npx playwright install
      shell: bash

    - name: Run E2E
      uses: segevgr/JamLive/.github/actions/retry@master
      with:
        command: |
          cd e2e
          npm test