name: E2E Tests
description: Run end-to-end Playwright tests
author: Segev Grotas

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20.10

    - name: Store/Restore node_modules cache
      uses: actions/cache@v4
      with:
        path: e2e/node_modules
        key: ${{ runner.os }}-e2e-${{ hashFiles('e2e/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-e2e-

    - name: Install & Run E2E
      run: |
        cd e2e
        npm ci
        npx playwright install --with-deps
        npm test
      shell: bash
