name: E2E Tests
description: Run end-to-end Playwright tests
author: Segev Grotas

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: "20.10.0"

    - name: Store/Restore node_modules cache
      uses: actions/cache@v4
      with:
        path: e2e/node_modules
        key: ${{ runner.os }}-e2e-${{ hashFiles('e2e/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-e2e-

    - name: Store/Restore Playwright browsers cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          playwright-${{ runner.os }}-


    - name: Install & Run E2E
      run: |
        cd e2e
        npm ci
        npx playwright install --with-deps
        npx playwright test --trace on
      shell: bash

    - name: Upload Playwright trace (on failure)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-trace
        path: e2e/test-results/**/*.zip
        retention-days: 1
