name: E2E Tests
description: Run end-to-end Playwright tests
author: Segev Grotas

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: "20.10.0"

    - name: Store/Restore node_modules cache
      uses: actions/cache@v4
      with:
        path: e2e/node_modules
        key: ${{ runner.os }}-e2e-${{ hashFiles('e2e/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-e2e-

    - name: Store/Restore Playwright browsers cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          playwright-${{ runner.os }}-

    - name: Install & Run E2E
      working-directory: e2e
      run: |
        if [ ! -d "node_modules" ] || [ -z "$(ls -A node_modules)" ]; then
          echo "No node_modules cache found. Running npm ci."
          npm ci
        else
          echo "node_modules cache restored. Skipping npm ci."
        fi
        npx playwright install
        npm test
      shell: bash
