name: build-and-unit-test

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      should_run:
        required: true
        type: string

jobs:
  always_success:
    runs-on: ubuntu-latest
    steps:
      - name: Mark workflow as success when no changes
        run: echo "This job ensures workflow never ends as skipped."

  build_and_test:
    runs-on: ubuntu-latest
    if: ${{ inputs.should_run == 'true' }}
    defaults:
      run:
        working-directory: ${{ inputs.project }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"
      - run: npm ci
      - run: npm run build
      - run: npm test
