name: build-and-unit-test

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      should_run:
        required: true
        type: string

jobs:
  always_success:
    runs-on: ubuntu-latest
    steps:
      - name: Mark workflow as success when no changes
        run: echo "This job ensures workflow never ends as skipped"

  build_and_test:
    runs-on: ubuntu-latest
    if: ${{ inputs.should_run == 'true' }}
    defaults:
      run:
        working-directory: ${{ inputs.project }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Builder Stage (cache only)
        uses: docker/build-push-action@v6
        with:
          context: ./${{ inputs.project }}
          push: false
          load: false
          target: builder
          tags: jamlive/${{ inputs.project }}:builder
          cache-from: type=gha,scope=${{ inputs.project }}
          cache-to: type=gha,scope=${{ inputs.project }},mode=max

      - name: Run Unit Tests
        run: |
          docker build --target unit-tests -t jamlive/${{ inputs.project }}-test .