name: build-and-unit-test

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      should_run:
        required: true
        type: string
      timeout-minutes:
        required: false
        type: number

permissions:
  packages: write

jobs:
  always_success:
    runs-on: ubuntu-latest
    steps:
      - name: Mark workflow as success when no changes
        run: echo "This job ensures workflow never ends as skipped"

  build_and_test:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout-minutes }}
    if: ${{ inputs.should_run == 'true' }}
    defaults:
      run:
        working-directory: ${{ inputs.project }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_ACCESS_TOKEN }}

      - name: Stabilize timestamps
        run: git ls-files | xargs touch --date="@$(git log -1 --format=%ct)"

      - name: Build Builder Stage (cache only)
        uses: docker/build-push-action@v6
        env:
          OWNER: segevgr
        with:
          context: ./${{ inputs.project }}
          push: true
          load: false
          build-args: |
            BUILDKIT_INLINE_CACHE=1
          target: builder
          tags: ghcr.io/${{ env.OWNER }}/${{ inputs.project }}:builder
          cache-from: type=gha,scope=${{ inputs.project }},mode=max
          cache-to: |
            type=gha,scope=${{ inputs.project }},mode=max
            type=inline,mode=max,compression=uncompressed
            type=registry,ref=ghcr.io/${{ env.OWNER }}/${{ inputs.project }}:builder,mode=max

      - name: Debug inline cache (raw)
        run: |
          echo "🔎 raw manifest:"
          docker buildx imagetools inspect ghcr.io/segevgr/${{ inputs.project }}:builder --raw | sed -n '1,120p'
          echo "🔎 search for cache.v0:"
          docker buildx imagetools inspect ghcr.io/segevgr/${{ inputs.project }}:builder --raw | grep -n "org.mobyproject.buildkit.cache.v0" || echo "❌ cache.v0 not found in raw output"

      - name: Run Unit Tests
        uses: docker/build-push-action@v6
        with:
          context: ./${{ inputs.project }}
          target: unit-tests
          tags: jamlive/${{ inputs.project }}-test
          push: false
          load: false
          build-args: |
            BUILDKIT_INLINE_CACHE=1
          cache-from: type=gha,scope=${{ inputs.project }},mode=max
