name: jamlive-ci

on:
  push:
    branches: ["master"]
    paths-ignore:
      - "README.md"
  workflow_dispatch:

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Detect file changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - 'frontend/src/**'
            backend:
              - 'backend/src/**'

  build_and_unit_tests:
    runs-on: ubuntu-latest
    name: Build and Unit Tests (${{ matrix.project }})
    needs: detect_changes
    if: ${{ needs.detect_changes.outputs.frontend == 'true' || needs.detect_changes.outputs.backend == 'true' }}
    strategy:
      matrix:
        project: [frontend, backend]
    defaults:
      run:
        working-directory: ${{ matrix.project }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.10

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Tests
        run: npm test

  package_e2e_tests_and_deploy:
    runs-on: ubuntu-latest
    name: Package E2E Tests and Deploy
    needs: build_and_unit_tests
    if: ${{ success() || needs.build_and_unit_tests.result == 'skipped' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Docker Compose
        run: docker compose up --build -d
        env:
          PORT: 8000
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
          JWT_COOKIE_EXPIRES_IN: ${{ secrets.JWT_COOKIE_EXPIRES_IN }}
          FRONTEND_ORIGIN: ${{ secrets.FRONTEND_ORIGIN }}
          E2E_BASE_URL: ${{ secrets.E2E_BASE_URL }}
          REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}

      # - name: Backend E2E Testing
      #   working-directory: backend
      #   run: npm run test:e2e

      ########### TBD - E2E TESTING ###########

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGIONS }}

      - name: Export frontend build
        run: |
          container_id=$(docker ps -qf "ancestor=jamlive-front:test")
          echo "Frontend container: $container_id"
          docker cp $container_id:/app/build ./frontend_build
          ls -la ./frontend_build

      - name: List frontend build contents
        run: ls -la ./frontend_build

      - name: Deploy Frontend to S3
        run: aws s3 sync ./frontend_build s3://${{ secrets.AWS_S3_BUCKET }} --delete
