name: jamlive-ci

on:
  push:
    branches: ["master"]
    paths-ignore:
      - "README.md"
      - "postman/**"
      - "screenshots/**"
      - "terraform/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  packages: write

concurrency:
  group: jamlive-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cancel-previous:
    name: Cancel Previous Workflow Runs
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

  detect_changes:
    name: Detect Code Changes
    needs: cancel-previous
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect file changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'

  build_and_unit_test:
    name: Build & Unit Tests (${{ matrix.service }})
    needs: [detect_changes]
    uses: ./.github/workflows/build-lint-and-unit-test.yaml
    secrets: inherit
    permissions:
      packages: write
    strategy:
      matrix:
        service: [frontend, backend]
    with:
      service: ${{ matrix.service }}
      should_run: ${{ needs.detect_changes.outputs[matrix.service] }}
      timeout-minutes: 30

  package_runners:
    name: Package ${{ matrix.service }} Runner
    needs: [build_and_unit_test]
    uses: ./.github/workflows/package-runner.yaml
    secrets: inherit
    permissions:
      packages: write
    strategy:
      matrix:
        service: [frontend, backend]
    with:
      service: ${{ matrix.service }}
      timeout-minutes: 30
      repo-owner: segevgr

  e2e_tests_and_publish:
    name: Package E2E Tests and Publish
    needs: [package_runners]
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      OWNER: segevgr
    outputs:
      version_tag: ${{ steps.version.outputs.new_tag }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_ACCESS_TOKEN }}

      - name: Pull images built in previous jobs
        run: |
          docker pull ghcr.io/${{ env.OWNER }}/frontend:runner
          docker pull ghcr.io/${{ env.OWNER }}/backend:runner
          docker tag ghcr.io/${{ env.OWNER }}/frontend:runner jamlive/frontend:test
          docker tag ghcr.io/${{ env.OWNER }}/backend:runner jamlive/backend:test

      - name: Run Docker Compose
        env:
          MONGO_URI: "mongodb://db:27017/jamlive_dev"
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: docker compose up -d

      - name: Wait for all Docker services to be healthy
        uses: raschmitt/wait-for-healthy-container@v1.0.1
        with:
          container-name: jamlive-frontend
          timeout: 30

      - name: E2E Tests
        uses: ./.github/actions/e2e-tests

      - name: Fetch Version
        id: version
        uses: ./.github/actions/version-increment

      - name: Configure AWS
        uses: ./.github/actions/configure-aws
        with:
          aws_role_arn: ${{ secrets.ECR_ROLE_ARN }}
          aws_region: ${{ secrets.AWS_REGION }}

      - name: Publish Backend Image To ECR
        uses: ./.github/actions/publish-to-ecr
        with:
          local_image: jamlive/backend:test
          repo_uri: ${{ secrets.BACKEND_ECR_URI }}
          tag: ${{ steps.version.outputs.new_tag }}

      - name: Publish Frontend Image To ECR
        uses: ./.github/actions/publish-to-ecr
        with:
          local_image: jamlive/frontend:test
          repo_uri: ${{ secrets.FRONTEND_ECR_URI }}
          tag: ${{ steps.version.outputs.new_tag }}

      - name: Export Frontend Build
        run: |
          container_id=$(docker ps -qf "ancestor=jamlive/frontend:test")
          docker cp $container_id:/app/build ./frontend_build

      - name: Publish Frontend Build as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend_build
          path: ./frontend_build
          retention-days: 1

  deploy_frontend:
    name: Deploy Frontend
    needs: e2e_tests_and_publish
    uses: ./.github/workflows/frontend-cd.yaml
    secrets: inherit
    permissions:
      id-token: write
    with:
      artifact: frontend_build
      version: ${{ needs.e2e_tests_and_publish.outputs.version_tag }}

  # deploy_backend:
  #   name: Deploy Backend
  #   needs: e2e_tests_and_publish
  #   uses: ./.github/workflows/backend-cd.yaml
  #   secrets: inherit
  #   permissions:
  #     id-token: write
  #   with:
  #     artifact: backend_build

  create_git_tag:
    name: Create Git Tag from Version
    runs-on: ubuntu-latest
    # needs: [e2e_tests_and_publish, deploy_frontend, deploy_backend]
    needs: [e2e_tests_and_publish, deploy_frontend]
    
    steps:
      - uses: actions/checkout@v4

      - run: |
          git tag ${{ needs.e2e_tests_and_publish.outputs.version_tag }}
          git push origin ${{ needs.e2e_tests_and_publish.outputs.version_tag }}

  notify:
    name: Notify
    if: always()
    needs:
      - cancel-previous
      - detect_changes
      - build_and_unit_test
      - package_runners
      - e2e_tests_and_publish
      - deploy_frontend
      # - deploy_backend
      - create_git_tag
    uses: ./.github/workflows/notify-by-email.yaml
    secrets: inherit
