name: package-runner

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      timeout-minutes:
        required: true
        type: number
      repo-owner:
        required: true
        type: string

permissions:
  packages: write

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_ACCESS_TOKEN }}

      - name: Pull cached builder image
        run: docker pull ghcr.io/${{ inputs.repo-owner }}/${{ inputs.service }}:builder

      - name: Build and Cache ${{ inputs.service }} Image
        uses: docker/build-push-action@v6
        env:
          BUILD_ARGS: ${{ inputs.service == 'frontend' && format('REACT_APP_BASE_URL={0}', secrets.BACKEND_URL) || '' }}
        with:
          context: ./${{ inputs.service }}
          push: true
          load: false
          target: runner
          tags: ghcr.io/${{ inputs.repo-owner }}/${{ inputs.service }}:runner
          build-args: ${{ env.BUILD_ARGS }}
          cache-from: |
            type=registry,ref=ghcr.io/${{ inputs.repo-owner }}/${{ inputs.service }}:builder
            type=registry,ref=ghcr.io/${{ inputs.repo-owner }}/${{ inputs.service }}:builder-cache
            type=registry,ref=ghcr.io/${{ inputs.repo-owner }}/${{ inputs.service }}:runner-cache
          cache-to: type=registry,ref=ghcr.io/${{ inputs.repo-owner }}/${{ inputs.service }}:runner-cache,mode=max
